# Generated by Django 3.0.10 on 2021-03-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_application_cached_latest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEventResult',
            fields=[
                ('application_event_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.ApplicationEvent')),
            ],
            bases=('applications.applicationevent',),
        ),
        migrations.CreateModel(
            name='ApplicationEventScheduleResult',
            fields=[
                ('application_event_schedule_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applications.ApplicationEventSchedule')),
                ('allocated_duration', models.DurationField()),
                ('allocated_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day')),
                ('allocated_begin', models.TimeField(verbose_name='Start')),
                ('allocated_end', models.TimeField(verbose_name='End')),
                ('application_event_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_event_schedule_results', to='applications.ApplicationEventResult')),
            ],
            bases=('applications.applicationeventschedule',),
        ),
    ]
