# Generated by Django 3.1.8 on 2021-04-12 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.datetime_safe import datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation_units', '0013_reservationunit_uuid'),
        ('applications', '0032_applicationeventscheduleresult'),
    ]

    def create_schedule_statuses(apps, schema_editor):
        ApplicationEventSchedule = apps.get_model("applications", "ApplicationEventSchedule")
        ApplicationEventScheduleStatus = apps.get_model("applications", "ApplicationEventScheduleStatus")
        for event in ApplicationEventSchedule.objects.all():
            status = ApplicationEventScheduleStatus.objects.create(
                application_event_schedule=event,
                timestamp=datetime.now(),
                status="created"
            )
            status.save()

    operations = [
        migrations.AddField(
            model_name='applicationeventschedule',
            name='declined_reservation_units',
            field=models.ManyToManyField(blank=True, to='reservation_units.ReservationUnit', verbose_name='Declined reservation units'),
        ),
        migrations.CreateModel(
            name='ApplicationEventScheduleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('declined', 'Declined')], max_length=20, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('application_event_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='applications.applicationeventschedule', verbose_name='Application event schedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.RunPython(
            create_schedule_statuses, migrations.RunPython.noop
        ),
    ]
