# Generated by Django 3.1.13 on 2021-11-05 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0049_missing_translated_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationevent',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='applicationround',
            name='purposes',
        ),
        migrations.RemoveField(
            model_name='applicationroundbasket',
            name='purposes',
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='reservations.reservationpurpose', verbose_name='Reservation purpose'),
        ),
        migrations.AddField(
            model_name='applicationround',
            name='purposes',
            field=models.ManyToManyField(related_name='application_rounds', to='reservations.ReservationPurpose',
                                         verbose_name='Reservation purposes'),
        ),
        migrations.AddField(
            model_name='applicationroundbasket',
            name='purposes',
            field=models.ManyToManyField(blank=True, to='reservations.ReservationPurpose',
                                         verbose_name='Reservation purposes'),
        ),
    ]
