# Generated by Django 3.0.10 on 2021-02-03 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesectorrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_sector_roles', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
