# Generated by Django 3.1.13 on 2021-11-04 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservee_first_and_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationpurpose',
            name='custom_purpose',
        ),
        migrations.RemoveField(
            model_name='reservationpurpose',
            name='custom_purpose_en',
        ),
        migrations.RemoveField(
            model_name='reservationpurpose',
            name='custom_purpose_fi',
        ),
        migrations.RemoveField(
            model_name='reservationpurpose',
            name='custom_purpose_sv',
        ),
        migrations.RemoveField(
            model_name='reservationpurpose',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='reservationpurpose',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='custom_purpose',
            field=models.TextField(blank=True, verbose_name='Custom purpose'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservationpurpose', verbose_name='Reservation purpose'),
        ),
        migrations.AddField(
            model_name='reservationpurpose',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationpurpose',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservationpurpose',
            name='name_fi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservationpurpose',
            name='name_sv',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
